BlogMenuCut add localeStorage to stay on selected category after reload
slavo3dev/slavo pull request #60
Opened 2024-10-08 10:51 UTC by SdZika

Modify BlogManuCut component on blog page, so after reload user stay on selected category. Also add "windows" value in "rules" object in .eslintrc.json to accept linebrake-stayle for windows

2024-10-09 20:12 UTC, slavo3dev commented on .eslintrc.json
> +		"linebreak-style": ["error", "unix", "windows"],
What this line fix??

2024-10-09 20:14 UTC, slavo3dev commented on components/Posts/BlogMenuCat/index.tsx
> +	const [activeCategory, setActiveCategory] = useState<string>("");
we don't want to repeat the code, please create a custom hook for this. 

and those hooks you can place in 
lib/hooks/hookname.ts

2024-10-09 20:16 UTC, slavo3dev requested changes
Please fix address issues

2024-10-10 23:04 UTC, slavo3dev commented
Do we need this PR

2024-10-11 07:13 UTC, closed without merging

2024-10-11 07:15 UTC, SdZika commented
Deprecated branch