WIP...Login/popup window
slavo3dev/slavo pull request #82
Opened 2024-11-09 22:28 UTC by Milutin25

Styled login modal for porch-check your stats button(when clicked login modal shows).
Need to implement this wherever user is asked to be logged in.

2024-11-13 21:47 UTC, slavo3dev commented on components/FreeSourcesList/index.tsx
> +  setFacts: any;
we need to fix this , we can not do any

2024-11-13 21:48 UTC, slavo3dev commented on components/Layout/CardsLayout/index.tsx
> +  extraContent?: React.ReactNode;
import ReactNode

2024-11-13 21:48 UTC, slavo3dev commented on components/PorchElements/PorchHeader/index.tsx
> +import React, { useContext, useState, useEffect } from "react";
remove react

2024-11-13 21:49 UTC, slavo3dev requested changes
Small changes , lGTM

2024-11-20 11:21 UTC, SdZika approved these changes
All good.

2024-12-12 21:38 UTC, slavo3dev approved these changes

2024-12-12 21:44 UTC, merged